### PR TITLE
Update main.geojson for new markers in DECC

### PR DESCRIPTION
**Pull request by mmdolbow**
Putting this in a pull request instead of commiting directly to pages, because 1) the new data doesn't fit the scheme 2) I'm not sure the styling will work well with all these additional points 3) it might look a bit cluttered if the styling does work and 4) then again, it might break entirely! :-)

### CODE REVIEW

**Comment by geospatialem** [comment]
So, I'm not a huge fan of the look since it adds a bit of clutter... here's what it looks like on load:
map-screen-shot

As you mentioned, it doesn't follow the current structure, so the popup looks a little odd...

That being said, I'm not opposed to adding it in, but **_what would you think of the following methodology instead?_**:
1. Use a polygon style instead (it could be _deccLayout.geojson_, or an entirely new file as well).
2. Break out the regions of the DECC using the polygon.
3. We add it to the map by grouping it with the main.geojson file (and add those layers as checkboxes, instead of the current radio button)

... Thoughts?
/cc #5

**Comment by mmdolbow** [comment]
I like the idea of having a separate check box or a scale dependency to toggle these details - they're only pertinent when zoomed way in, and only when someone wants to know. We can certainly do polygons, although that's more complicated. Another option would be points with much smaller icons so they are less distracting. Your call, I will execute as desired. Final question: should we have separate layers for the different floors, or one layer where the floor is identified in the properties?

**Comment by mmdolbow** [comment]
As resolved in discussion: I will make two new layers of polygons, one for each floor, and commit to the master.

**Comment by geospatialem** [comment]
Thanks! Closing this PR since we are going in a different direction. Looking forward to those geojson's!

**Pull request closed without merging**
